// typescript/native-auth/react-nextjs-sample/src/app/shared/components/MfaAuthMethodSelectionForm.tsx
import React from "react";
import type { MfaAuthMethodSelectionFormProps } from "../types/formProperties";

export const MfaAuthMethodSelectionForm: React.FC<MfaAuthMethodSelectionFormProps> = ({
    onSubmit,
    authMethods,
    selectedAuthMethod,
    setSelectedAuthMethod,
    loading,
    styles,
    title = "Select a verification method to complete multi-factor (second factor) authentication",
}) => {
    return (
        <div>
            <h3
                style={{
                    marginBottom: "1rem",
                    color: "#374151",
                    fontSize: "1rem",
                    fontWeight: 500,
                    textAlign: "center",
                }}
            >
                {title}
            </h3>
            <form onSubmit={onSubmit} style={styles.form}>
                <select
                    value={selectedAuthMethod?.challenge_channel || ""}
                    onChange={(e) => {
                        const selected = authMethods.find((method) => method.challenge_channel === e.target.value);
                        setSelectedAuthMethod(selected);
                    }}
                    style={{ ...styles.input, textTransform: "capitalize" as const }}
                    required
                >
                    {authMethods.map((method) => (
                        <option key={method.challenge_channel} value={method.challenge_channel}>
                            {method.challenge_channel}
                        </option>
                    ))}
                </select>
                <button
                    type="submit"
                    disabled={loading || !selectedAuthMethod}
                    style={loading || !selectedAuthMethod ? styles.buttonDisabled : styles.button}
                >
                    {loading ? "Loading..." : "Choose"}
                </button>
            </form>
        </div>
    );
};

// typescript/native-auth/angular-sample/src/app/components/shared/mfa-auth-method-selection-form/mfa-auth-method-selection-form.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { AuthenticationMethod } from "@azure/msal-browser/custom-auth";

@Component({
    selector: "app-mfa-auth-method-selection-form",
    templateUrl: "./mfa-auth-method-selection-form.component.html",
    standalone: true,
    imports: [CommonModule, FormsModule],
})
export class MfaAuthMethodSelectionFormComponent {
    @Input() authMethods: AuthenticationMethod[] = [];
    @Input() selectedAuthMethod: AuthenticationMethod | undefined;
    @Input() loading = false;
    @Input() title = "Select a verification method to complete multi-factor (second factor) authentication";
    @Input() submitButtonText = "Choose";
    @Input() submitButtonLoadingText = "Loading...";

    @Output() selectedAuthMethodChange = new EventEmitter<AuthenticationMethod | undefined>();
    @Output() submitForm = new EventEmitter<void>();

    onAuthMethodChange(method: AuthenticationMethod | undefined) {
        this.selectedAuthMethodChange.emit(method);
    }

    onSubmit() {
        this.submitForm.emit();
    }
}

<form (ngSubmit)="onSubmit()">
    <h3>{{ title }}</h3>
    <div class="auth-methods">
        <select class="auth-method-select" [ngModel]="selectedAuthMethod" (ngModelChange)="onAuthMethodChange($event)"
            name="authMethod" required>
            <option *ngFor="let authMethod of authMethods" [ngValue]="authMethod">
                {{ authMethod.challenge_channel }}
            </option>
        </select>
    </div>
    <button type="submit" [disabled]="loading || !selectedAuthMethod">
        {{ loading ? submitButtonLoadingText : submitButtonText }}
    </button>
</form>
