// typescript/native-auth/react-nextjs-sample/src/app/shared/components/MfaChallengeForm.tsx
import React from "react";
import type { MfaChallengeFormProps } from "../types/formProperties";

export const MfaChallengeForm: React.FC<MfaChallengeFormProps> = ({
    onSubmit,
    challenge,
    setChallenge,
    loading,
    styles,
    title = "Enter the code below to verify your selected authentication method",
}) => {
    return (
        <div>
            <h3
                style={{
                    marginBottom: "1rem",
                    color: "#374151",
                    fontSize: "1rem",
                    fontWeight: 500,
                    textAlign: "center",
                }}
            >
                {title}
            </h3>
            <form onSubmit={onSubmit} style={styles.form}>
                <input
                    type="text"
                    value={challenge}
                    onChange={(e) => setChallenge(e.target.value)}
                    placeholder="Enter verification code"
                    style={styles.input}
                    required
                />
                <button
                    type="submit"
                    disabled={loading || !challenge}
                    style={loading || !challenge ? styles.buttonDisabled : styles.button}
                >
                    {loading ? "Verifying..." : "Verify Code"}
                </button>
            </form>
        </div>
    );
};

// typescript/native-auth/angular-sample/src/app/components/shared/mfa-challenge-form/mfa-challenge-form.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";

@Component({
    selector: "app-mfa-challenge-form",
    templateUrl: "./mfa-challenge-form.component.html",
    standalone: true,
    imports: [CommonModule, FormsModule],
})
export class MfaChallengeFormComponent {
    @Input() challenge: string | undefined = "";
    @Input() loading = false;
    @Input() title = "Enter the code below to verify your selected authentication method";
    @Input() placeholder = "Enter verification code";
    @Input() submitButtonText = "Verify Code";
    @Input() submitButtonLoadingText = "Verifying...";

    @Output() challengeChange = new EventEmitter<string>();
    @Output() submitForm = new EventEmitter<void>();

    onChallengeChange(value: string) {
        this.challengeChange.emit(value);
    }

    onSubmit() {
        this.submitForm.emit();
    }
}

<form (ngSubmit)="onSubmit()">
    <h3>{{ title }}</h3>
    <div class="form-field">
        <input type="text" [value]="challenge || ''" (input)="onChallengeChange($any($event.target).value)"
            [placeholder]="placeholder" [disabled]="loading" required />
    </div>
    <button type="submit" [disabled]="loading || !challenge">
        {{ loading ? submitButtonLoadingText : submitButtonText }}
    </button>
</form>
